config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount API::Base, at: "/"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :meeting_rooms do
    resources :reservations do
      get 'cancle', on: :member
    end
  end

  resources :users
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/device.rb
class Device < ActiveRecord::Base
  has_one :meeting_room
end

app/models/meeting_room.rb
class MeetingRoom < ActiveRecord::Base
  has_many :reservations
  belongs_to :device

  def preset(room_id)
    16.times do |i|
      Reservation.create(
        topic: "Open for everyone",
        date: Time.current,
        from: Time.current.beginning_of_hour+1800*(i+1),
        to: Time.current.beginning_of_hour+3600*(i+1),
        meeting_room_id: room_id
      )
    end
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :meeting_room
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations
end

app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::V1::Base
  end
end

app/controllers/api/v1/base.rb
module API
  module V1
    class Base < Grape::API
      mount API::V1::Reservations
      mount API::V1::Devices
    end
  end
end

app/controllers/api/v1/data_patterns.rb
module API
  module V1
    module DataPatterns
      extend ActiveSupport::Concern

      included do
        prefix "api"
        version "v1", using: :path
        default_format :json
        format :json

        helpers do
          def meeting_room_pattern(meeting_room)
            {
              'id': meeting_room.id,
              'name': meeting_room.name,
              'status': meeting_room.status,
              'device': meeting_room.device&.hwid || 'not bind',
              'updated_at': meeting_room.updated_at
            }
          end

          def device_pattern(device)
            {
              'id': device.id,
              'HWID': device.hwid,
              'active': device.active,
              'meeting room': device.meeting_room&.name || 'not bind',
              'last update': device.updated_at
            }
          end

          def reservation_pattern(reservation)
            {
              'id': reservation.id,
              'topic': reservation.topic,
              'date': reservation.date,
              'from': reservation.from,
              'to': reservation.to,
              'MeetingRoom': reservation.meeting_room&.name || 'not taken',
              'user': reservation.user&.name || 'not taken',
              'taken': reservation.taken
            }
          end

          def user_pattern(user)
            {
              'id': user.id,
              'name': user.name
            }
          end
        end
      end
    end
  end
end

app/controllers/api/v1/defaults.rb
module API
  module V1
    module Defaults
      extend ActiveSupport::Concern

      included do
        prefix "api"
        version "v1", using: :path
        default_format :json
        format :json

        helpers do
          def permitted_params
            @permitted_params ||= declared(params,
               include_missing: false)
          end

          def logger
            Rails.logger
          end

          def set_return(status, message = [], result = [], code = 404)
            {
              status: status,
              message: message,
              result: result,
              code: code
            }
          end
        end

        rescue_from ActiveRecord::RecordNotFound do |e|
          error_response(message: e.message, status: 404)
        end

        rescue_from ActiveRecord::RecordInvalid do |e|
          error_response(message: e.message, status: 422)
        end
      end
    end
  end
end

app/controllers/api/v1/devices.rb
module API
  module V1
    class Devices < Grape::API
      include API::V1::Defaults
      include API::V1::DataPatterns

      resource :devices do
        desc 'Return all devices'
        get '', root: :devices do
          devices = Device.all
          return set_return('error', 'can not find any device') if devices.nil?
          all_devices = []
          devices.each do |device|
            all_devices << device_pattern(device)
          end
          set_return('success', 'found device', all_devices, 200)
        end

        desc 'Return a device'
        params do
          requires :hwid, type: String, desc: 'Hardware ID'
        end
        get ':hwid', root: 'device' do
          device = Device.find_by(hwid: permitted_params[:hwid])
          return set_return('error', 'can not find associate device') if device.nil?
          set_return('success', 'found device', meeting_room_pattern(device.meeting_room), 200)
        end
      end
    end
  end
end

app/controllers/api/v1/reservations.rb
module API
  module V1
    class Reservations < Grape::API
      include API::V1::Defaults
      include API::V1::DataPatterns

      resource :reservations do
        desc "Return all reservations"
        get '', root: :reservations do
          reservations = Reservation.all
          return set_return('error', 'can not find any reservation') if reservations.nil?
          all_reservation = []
          reservations.each do |reservation|
            all_reservation << reservation_pattern(reservation)
          end
          set_return('success', 'found device', all_reservation, 200)
        end

        desc "Return a reservation"
        params do
          requires :id, type: String, desc: 'ID of the reservation'
        end
        get ":id", root: "reservation" do
          reservation = Reservation.find(permitted_params[:id])
          return set_return('error', 'can not find any reservation') if reservation.nil?
          set_return('success', 'found reservation', reservation_pattern(reservation), 200)
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meeting_rooms_controller.rb
class MeetingRoomsController < ApplicationController
  def index
    @meeting_rooms = MeetingRoom.all
  end

  def show
    @meeting_room = MeetingRoom.find(params[:id])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(
      topic: params[:reservation][:topic],
      user_id: params[:reservation][:user_id],
      taken: true)

      redirect_to meeting_room_path(params[:meeting_room_id])
    else
      redirect_to edit_meeting_room_reservation_path(meeting_room.id, @reservation.id)
    end
  end

  def cancle
    @reservation = Reservation.find(params[:id])
    if @reservation.update(
      topic: "Open for everyone",
      user_id: nil,
      taken: false)

      redirect_to user_path(1) #current_user
    else
      redirect_to meeting_rooms_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meeting_rooms_helper.rb
module MeetingRoomsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalendarApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/meeting_rooms/index.html.erb
<div style="width: 100%;">
<% @meeting_rooms.each do |room| %>
  <div style="background-color: yellow;">
    <div style="text-align: center;">
      <h1><%= room.name %></h1>
    </div>
    <div style="text-align: center;">
      <h3>Current Status: <%= room&.status || 'Vacant' %></h3>
    </div>
    <div style="text-align: center; margin: 5vh;">
      <span>
        <%= link_to 'View', meeting_room_path(room) %>
      </span>
    </div>
  </div>
<% end %>
</div>

app/views/meeting_rooms/show.html.erb
<div style="text-align: center; margin: 2.5vh;">
  <h1><%= @meeting_room.name %></h1>
</div>
<div style="text-align: center;">
<% @meeting_room.reservations.where(taken: false).group_by(&:date).each_pair do |date, reservation| %>
  <h4>Date: <%= date %></h4>
  <% reservation.each do |res| %>
    <div style="padding: 10px;">
      <div>
        <%= res.from.strftime('%H:%M') %> - <%= res.to.strftime('%H:%M') %>
      </div>
      <div>
        <%= link_to 'Take Resevation', edit_meeting_room_reservation_path(@meeting_room.id, res) %></h1>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/reservations/edit.html.erb
<div style="text-align: center;">
  <h1>Reservation Form</h1>
</div>
<div class="form-group">
  <%= form_for @reservation, url: meeting_room_reservation_path do |f| %>
    <div class="form-group">
      <h2><%= f.label :topic, "Please Enter you Topic" %></h2>
    </div>
    <div class="form-group">
      <%= f.text_field :topic, class: "form-control", require: true %>
    </div>
    <%= f.hidden_field :user_id, value: 1 %>
    <div style="display: block; margin: auto;">
      <%= f.submit "Take a Reservation", class: "btn btn-warning"%>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div style="text-align: center;">
  <h1><%= @user.name %></h1>
</div>
<div style="text-align: center;">
  My Meeting Reservation
</div>
<div style="text-align: center;">
<% @user.reservations.group_by(&:date).each_pair do |date, reservation| %>
  <h4>Date: <%= date %></h4>
  <% reservation.each do |res| %>
    <div style="padding: 10px;">
      <div>
        <%= res.from.strftime('%H:%M') %> - <%= res.to.strftime('%H:%M') %>
      </div>
      <div>
        <%= link_to 'Cancle', cancle_meeting_room_reservation_path(res.meeting_room_id, res.id) %>
      </div>
    </div>
  <% end %>
<% end %>
</div>